// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6dpA8wbATYECJraKxBaJR4D1GSLD78ys',
    appId: '1:131823254230:web:ed7cc99bb88d435a702777',
    messagingSenderId: '131823254230',
    projectId: 'notes-9e379',
    authDomain: 'notes-9e379.firebaseapp.com',
    storageBucket: 'notes-9e379.appspot.com',
    measurementId: 'G-528VEPWL18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIwKIvSLLKDVHviAfZ8SUbqvj5aoL6r4E',
    appId: '1:131823254230:android:7c2340975aa7db44702777',
    messagingSenderId: '131823254230',
    projectId: 'notes-9e379',
    storageBucket: 'notes-9e379.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn80eoB2NAjWHEYBLtLa1xWpx4LRt29KU',
    appId: '1:131823254230:ios:633dd9b2633d13a7702777',
    messagingSenderId: '131823254230',
    projectId: 'notes-9e379',
    storageBucket: 'notes-9e379.appspot.com',
    iosBundleId: 'com.ronakj.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn80eoB2NAjWHEYBLtLa1xWpx4LRt29KU',
    appId: '1:131823254230:ios:db5b316b89b7501a702777',
    messagingSenderId: '131823254230',
    projectId: 'notes-9e379',
    storageBucket: 'notes-9e379.appspot.com',
    iosBundleId: 'com.ronakj.notesapp.RunnerTests',
  );
}
